window.EXPOSURE_SEEDS = {
  network: [
    {id:'NET-001',score:9.4,title:'CVE-2024-1234 in OpenSSL 3.0.7',cve:'CVE-2024-1234',asset:'srv-payments-prod-04',owner:'Payments Platform',status:'Open',sla:'24h left',kev:true,internet:true,tool:'Tenable Nessus'},
    {id:'NET-002',score:6.1,title:'Apache httpd 2.4.49 path traversal',cve:'CVE-2021-41773',asset:'web-marketing-01',owner:'Marketing Web',status:'In progress',sla:'3d left',kev:true,internet:true,tool:'Qualys VMDR'},
    {id:'NET-003',score:5.2,title:'SMBv1 enabled',cve:null,asset:'47 hosts',owner:'Infrastructure',status:'Open',sla:'7d',kev:false,internet:false,tool:'Rapid7 InsightVM'},
    {id:'NET-004',score:8.8,title:'Exchange ProxyShell chain',cve:'CVE-2021-34473',asset:'exchange-prod-01',owner:'Messaging',status:'Compensating control',sla:'12h left',kev:true,internet:false,tool:'Tenable Nessus'},
    {id:'NET-005',score:7.4,title:'RDP exposed to internet',cve:null,asset:'12 hosts',owner:'Network',status:'Open',sla:'Overdue 2d',kev:true,internet:true,tool:'Qualys VMDR'},
    {id:'NET-006',score:3.8,title:'TLS 1.0 enabled',cve:null,asset:'api-gateway-02',owner:'API Platform',status:'Risk accepted',sla:'30d',kev:false,internet:true,tool:'Tenable Nessus'},
    {id:'NET-007',score:4.9,title:'Default MySQL credentials',cve:null,asset:'db-reporting-04',owner:'Data Platform',status:'Open',sla:'5d',kev:false,internet:false,tool:'Rapid7 InsightVM'},
    {id:'NET-008',score:6.7,title:'Missing kernel update CVE-2024-1086',cve:'CVE-2024-1086',asset:'200 RHEL hosts',owner:'Linux Ops',status:'In progress',sla:'4d left',kev:false,internet:false,tool:'Qualys VMDR'},
    {id:'NET-009',score:4.2,title:'Self-signed certificate',cve:null,asset:'edge-cdn-03',owner:'Network',status:'Open',sla:'14d',kev:false,internet:true,tool:'Tenable Nessus'},
    {id:'NET-010',score:7.1,title:'SNMPv2c community string public',cve:null,asset:'switch-core-12',owner:'Network',status:'Open',sla:'48h left',kev:false,internet:false,tool:'Rapid7 InsightVM'},
    {id:'NET-011',score:5.8,title:'SSH weak cipher suite',cve:null,asset:'bastion-jump-01',owner:'SecOps',status:'Patched',sla:'Closed',kev:false,internet:true,tool:'Qualys VMDR'},
    {id:'NET-012',score:8.2,title:'FortiOS SSL-VPN heap overflow',cve:'CVE-2024-21762',asset:'fw-edge-02',owner:'Network',status:'In progress',sla:'18h left',kev:true,internet:true,tool:'Tenable Nessus'},
    {id:'NET-013',score:3.4,title:'DNS zone transfer allowed',cve:null,asset:'dns-internal-01',owner:'Infrastructure',status:'Open',sla:'21d',kev:false,internet:false,tool:'Rapid7 InsightVM'},
    {id:'NET-014',score:6.3,title:'NTP monlist amplification',cve:'CVE-2013-5211',asset:'ntp-pool-04',owner:'Infrastructure',status:'Compensating control',sla:'6d',kev:false,internet:true,tool:'Qualys VMDR'},
    {id:'NET-015',score:7.9,title:'Citrix NetScaler memory leak',cve:'CVE-2023-4966',asset:'adc-payments-01',owner:'Payments Platform',status:'Open',sla:'36h left',kev:true,internet:true,tool:'Tenable Nessus'},
    {id:'NET-016',score:4.6,title:'ICMP timestamp enabled',cve:null,asset:'srv-legacy-22',owner:'Infrastructure',status:'Risk accepted',sla:'45d',kev:false,internet:false,tool:'Rapid7 InsightVM'},
    {id:'NET-017',score:5.5,title:'Telnet service listening',cve:null,asset:'lab-net-07',owner:'R&D',status:'Open',sla:'10d',kev:false,internet:false,tool:'Qualys VMDR'},
    {id:'NET-018',score:8.0,title:'VMware vCenter file upload',cve:'CVE-2021-22005',asset:'vcenter-mgmt-01',owner:'Virtualization',status:'In progress',sla:'2d left',kev:true,internet:false,tool:'Tenable Nessus'}
  ],
  sca: [
    {id:'SCA-001',score:9.7,title:'Log4Shell CVE-2021-44228',cve:'CVE-2021-44228',asset:'transaction-router',owner:'Payments Platform',status:'Open',sla:'12h left',kev:true,internet:true,tool:'Snyk Open Source'},
    {id:'SCA-002',score:5.1,title:'Vulnerable lodash 4.17.20',cve:'CVE-2020-8203',asset:'web-portal',owner:'Digital Experience',status:'In progress',sla:'5d left',kev:false,internet:true,tool:'Mend SCA'},
    {id:'SCA-003',score:8.2,title:'Malicious package event-stream',cve:null,asset:'internal-tool',owner:'Platform Engineering',status:'Open',sla:'24h left',kev:false,internet:false,tool:'Black Duck'},
    {id:'SCA-004',score:2.4,title:'Vulnerable urllib3 (not reachable)',cve:'CVE-2023-45803',asset:'batch-importer',owner:'Data Platform',status:'Risk accepted',sla:'60d',kev:false,internet:false,tool:'Snyk Open Source'},
    {id:'SCA-005',score:7.6,title:'Vulnerable spring-core',cve:'CVE-2022-22965',asset:'customer-api',owner:'Customer Apps',status:'Open',sla:'2d left',kev:false,internet:true,tool:'Snyk Open Source'},
    {id:'SCA-006',score:3.0,title:'GPL license leak',cve:null,asset:'mobile-sdk',owner:'Mobile',status:'Open',sla:'14d',kev:false,internet:false,tool:'Black Duck'},
    {id:'SCA-007',score:6.8,title:'jackson-databind deserialization',cve:'CVE-2020-36518',asset:'reporting-svc',owner:'Analytics',status:'Compensating control',sla:'4d',kev:false,internet:false,tool:'Mend SCA'},
    {id:'SCA-008',score:4.4,title:'Outdated axios SSRF',cve:'CVE-2023-45857',asset:'notify-worker',owner:'Messaging',status:'Patched',sla:'Closed',kev:false,internet:true,tool:'Snyk Open Source'},
    {id:'SCA-009',score:7.3,title:'Netty HTTP request smuggling',cve:'CVE-2023-44487',asset:'gateway-core',owner:'API Platform',status:'In progress',sla:'3d left',kev:false,internet:true,tool:'Snyk Open Source'},
    {id:'SCA-010',score:5.6,title:'Transitive commons-text RCE',cve:'CVE-2022-42889',asset:'etl-pipeline',owner:'Data Platform',status:'Open',sla:'6d',kev:false,internet:false,tool:'Mend SCA'},
    {id:'SCA-011',score:8.5,title:'Prototype pollution in minimist',cve:'CVE-2021-44906',asset:'cli-deployer',owner:'DevEx',status:'Open',sla:'36h left',kev:false,internet:false,tool:'Snyk Open Source'},
    {id:'SCA-012',score:1.9,title:'Dev dependency chalk (unused)',cve:null,asset:'docs-site',owner:'Developer Relations',status:'Risk accepted',sla:'90d',kev:false,internet:true,tool:'Snyk Open Source'},
    {id:'SCA-013',score:6.2,title:'Hibernate ORM SQL injection',cve:'CVE-2020-25638',asset:'inventory-api',owner:'Supply Chain',status:'Open',sla:'7d',kev:false,internet:false,tool:'Black Duck'},
    {id:'SCA-014',score:4.1,title:'Apache commons-compress zip slip',cve:'CVE-2021-36090',asset:'archive-svc',owner:'Platform Engineering',status:'In progress',sla:'9d left',kev:false,internet:false,tool:'Mend SCA'},
    {id:'SCA-015',score:7.0,title:'OkHttp certificate pinning bypass',cve:'CVE-2023-0833',asset:'android-checkout',owner:'Mobile',status:'Open',sla:'48h left',kev:false,internet:true,tool:'Snyk Open Source'},
    {id:'SCA-016',score:3.7,title:'Weak TLS in golang.org/x/crypto',cve:'CVE-2022-27191',asset:'auth-sidecar',owner:'Identity',status:'Patched',sla:'Closed',kev:false,internet:true,tool:'Snyk Open Source'},
    {id:'SCA-017',score:8.9,title:'XZ utils backdoor (supply chain)',cve:'CVE-2024-3094',asset:'build-ffmpeg',owner:'Build Systems',status:'Open',sla:'6h left',kev:true,internet:false,tool:'Black Duck'},
    {id:'SCA-018',score:5.0,title:'Electron ASAR integrity gap',cve:'CVE-2022-29247',asset:'desktop-agent',owner:'Endpoint Apps',status:'Compensating control',sla:'11d',kev:false,internet:false,tool:'Mend SCA'}
  ],
  sast: [
    {id:'SAST-001',score:8.9,title:'SQL injection in /charge',cve:null,asset:'payments-api',owner:'Payments Platform',status:'Open',sla:'24h left',kev:false,internet:true,tool:'Semgrep'},
    {id:'SAST-002',score:6.4,title:'Stored XSS in profile page',cve:null,asset:'admin-portal',owner:'Internal Apps',status:'In progress',sla:'4d left',kev:false,internet:true,tool:'Checkmarx'},
    {id:'SAST-003',score:8.1,title:'Hard-coded AWS access key',cve:null,asset:'legacy-batch.py',owner:'Data Platform',status:'Open',sla:'12h left',kev:false,internet:false,tool:'Veracode'},
    {id:'SAST-004',score:7.2,title:'Insecure deserialization',cve:null,asset:'report-generator',owner:'Analytics',status:'Open',sla:'3d left',kev:false,internet:false,tool:'Checkmarx'},
    {id:'SAST-005',score:5.5,title:'Broken authentication pattern',cve:null,asset:'internal-tool-svc',owner:'Platform Engineering',status:'Compensating control',sla:'8d',kev:false,internet:false,tool:'Semgrep'},
    {id:'SAST-006',score:7.8,title:'Path traversal in file upload',cve:null,asset:'file-upload-handler',owner:'Customer Apps',status:'In progress',sla:'2d left',kev:false,internet:true,tool:'Semgrep'},
    {id:'SAST-007',score:4.3,title:'Dead code: unused crypto API',cve:null,asset:'legacy-crypto-lib',owner:'Security Engineering',status:'Risk accepted',sla:'30d',kev:false,internet:false,tool:'Checkmarx'},
    {id:'SAST-008',score:6.9,title:'LDAP injection in search',cve:null,asset:'directory-sync',owner:'Identity',status:'Open',sla:'5d',kev:false,internet:false,tool:'Veracode'},
    {id:'SAST-009',score:3.2,title:'Log injection (low reach)',cve:null,asset:'audit-logger',owner:'SecOps',status:'Patched',sla:'Closed',kev:false,internet:false,tool:'Semgrep'},
    {id:'SAST-010',score:8.4,title:'Command injection in shell wrapper',cve:null,asset:'ops-runner',owner:'DevEx',status:'Open',sla:'18h left',kev:false,internet:false,tool:'Checkmarx'},
    {id:'SAST-011',score:5.9,title:'Weak random for session token',cve:null,asset:'session-mgr',owner:'Identity',status:'In progress',sla:'6d left',kev:false,internet:true,tool:'Semgrep'},
    {id:'SAST-012',score:7.5,title:'XXE in XML import parser',cve:null,asset:'invoice-import',owner:'Finance Systems',status:'Open',sla:'48h left',kev:false,internet:false,tool:'Veracode'},
    {id:'SAST-013',score:4.8,title:'Hard-coded JWT secret',cve:null,asset:'mobile-bff',owner:'Mobile',status:'Open',sla:'9d',kev:false,internet:true,tool:'Semgrep'},
    {id:'SAST-014',score:6.1,title:'Open redirect in OAuth callback',cve:null,asset:'sso-broker',owner:'Identity',status:'Compensating control',sla:'7d',kev:false,internet:true,tool:'Checkmarx'},
    {id:'SAST-015',score:2.8,title:'Unreachable branch: eval()',cve:null,asset:'feature-flags-old',owner:'Platform Engineering',status:'Risk accepted',sla:'45d',kev:false,internet:false,tool:'Semgrep'},
    {id:'SAST-016',score:7.7,title:'Server-side template injection',cve:null,asset:'email-renderer',owner:'Messaging',status:'Open',sla:'36h left',kev:false,internet:true,tool:'Veracode'},
    {id:'SAST-017',score:5.2,title:'Missing CSRF token on form',cve:null,asset:'hr-selfserve',owner:'HR Tech',status:'In progress',sla:'10d left',kev:false,internet:true,tool:'Checkmarx'},
    {id:'SAST-018',score:8.6,title:'Race condition in balance transfer',cve:null,asset:'ledger-core',owner:'Payments Platform',status:'Open',sla:'24h left',kev:false,internet:true,tool:'Veracode'}
  ],
  dast: [
    {id:'DAST-001',score:9.6,title:'Authentication bypass',cve:null,asset:'partners.example.com/auth',owner:'Partner Integrations',status:'Open',sla:'6h left',kev:true,internet:true,tool:'Burp Suite Enterprise'},
    {id:'DAST-002',score:8.7,title:'IDOR on /users/{id}/orders',cve:null,asset:'api.example.com',owner:'Customer Apps',status:'Open',sla:'12h left',kev:false,internet:true,tool:'OWASP ZAP'},
    {id:'DAST-003',score:8.3,title:'SSRF in /import?url=',cve:null,asset:'payments-api',owner:'Payments Platform',status:'In progress',sla:'24h left',kev:true,internet:true,tool:'Salt Security'},
    {id:'DAST-004',score:7.4,title:'Shadow API /internal/_debug',cve:null,asset:'api-gateway-prod',owner:'API Platform',status:'Open',sla:'2d left',kev:false,internet:true,tool:'Noname Security'},
    {id:'DAST-005',score:6.0,title:'Mass assignment on /profile/update',cve:null,asset:'user-profile-svc',owner:'Customer Apps',status:'Compensating control',sla:'5d',kev:false,internet:true,tool:'Burp Suite Enterprise'},
    {id:'DAST-006',score:7.1,title:'JWT alg:none accepted',cve:null,asset:'mobile-api',owner:'Mobile',status:'Open',sla:'3d left',kev:false,internet:true,tool:'OWASP ZAP'},
    {id:'DAST-007',score:5.4,title:'Clickjacking on checkout',cve:null,asset:'shop.example.com',owner:'E-commerce',status:'Risk accepted',sla:'21d',kev:false,internet:true,tool:'Burp Suite Enterprise'},
    {id:'DAST-008',score:8.0,title:'GraphQL introspection enabled',cve:null,asset:'graphql-federation',owner:'API Platform',status:'Open',sla:'36h left',kev:false,internet:true,tool:'Salt Security'},
    {id:'DAST-009',score:6.7,title:'CORS misconfiguration',cve:null,asset:'analytics-beacon',owner:'Marketing Web',status:'In progress',sla:'4d left',kev:false,internet:true,tool:'OWASP ZAP'},
    {id:'DAST-010',score:9.1,title:'SQLi in search parameter',cve:null,asset:'catalog-api',owner:'E-commerce',status:'Open',sla:'8h left',kev:false,internet:true,tool:'Burp Suite Enterprise'},
    {id:'DAST-011',score:4.9,title:'Verbose error stack traces',cve:null,asset:'staging-api',owner:'Platform Engineering',status:'Patched',sla:'Closed',kev:false,internet:true,tool:'OWASP ZAP'},
    {id:'DAST-012',score:7.6,title:'BOLA on /accounts/{id}',cve:null,asset:'banking-api',owner:'Finance Systems',status:'Open',sla:'48h left',kev:false,internet:true,tool:'Noname Security'},
    {id:'DAST-013',score:5.8,title:'Session fixation',cve:null,asset:'legacy-portal',owner:'Internal Apps',status:'Open',sla:'7d',kev:false,internet:true,tool:'Burp Suite Enterprise'},
    {id:'DAST-014',score:8.5,title:'XXE via SOAP upload',cve:null,asset:'erp-connector',owner:'Finance Systems',status:'In progress',sla:'1d left',kev:false,internet:false,tool:'OWASP ZAP'},
    {id:'DAST-015',score:3.6,title:'Missing security headers',cve:null,asset:'status-page',owner:'SRE',status:'Open',sla:'14d',kev:false,internet:true,tool:'OWASP ZAP'},
    {id:'DAST-016',score:6.5,title:'Rate limit bypass on OTP',cve:null,asset:'mfa-service',owner:'Identity',status:'Compensating control',sla:'6d',kev:false,internet:true,tool:'Salt Security'},
    {id:'DAST-017',score:7.9,title:'Web cache poisoning',cve:null,asset:'cdn-origin-app',owner:'Digital Experience',status:'Open',sla:'2d left',kev:false,internet:true,tool:'Burp Suite Enterprise'},
    {id:'DAST-018',score:5.1,title:'Host header injection',cve:null,asset:'marketing-landing',owner:'Marketing Web',status:'In progress',sla:'9d left',kev:false,internet:true,tool:'Noname Security'}
  ],
  container: [
    {id:'CON-001',score:9.4,title:'Log4j in deployed image',cve:'CVE-2021-44228',asset:'transaction-router:v4.2.1',owner:'Payments Platform',status:'Open',sla:'12h left',kev:true,internet:true,tool:'Trivy'},
    {id:'CON-002',score:7.2,title:'OS package CVE in node:16-alpine',cve:'CVE-2023-45853',asset:'node:16-alpine (47 svcs)',owner:'Platform Engineering',status:'In progress',sla:'3d left',kev:false,internet:true,tool:'Aqua Security'},
    {id:'CON-003',score:8.5,title:'Embedded secret in image layer',cve:null,asset:'deploy-tools:latest',owner:'DevEx',status:'Open',sla:'24h left',kev:false,internet:false,tool:'Sysdig Secure'},
    {id:'CON-004',score:8.0,title:'Privileged container + vuln kernel module',cve:null,asset:'monitoring-agent',owner:'Observability',status:'Compensating control',sla:'2d',kev:false,internet:false,tool:'Trivy'},
    {id:'CON-005',score:4.5,title:'CIS gap: :latest tag in prod',cve:null,asset:'23 deployments',owner:'Kubernetes Platform',status:'Open',sla:'10d',kev:false,internet:true,tool:'Aqua Security'},
    {id:'CON-006',score:7.8,title:'glibc CVE in distroless base',cve:'CVE-2023-4911',asset:'payments-svc:v2.1',owner:'Payments Platform',status:'Open',sla:'48h left',kev:false,internet:true,tool:'Trivy'},
    {id:'CON-007',score:6.4,title:'Writable root filesystem',cve:null,asset:'batch-worker',owner:'Data Platform',status:'In progress',sla:'5d left',kev:false,internet:false,tool:'Sysdig Secure'},
    {id:'CON-008',score:5.3,title:'Missing CPU/memory limits',cve:null,asset:'cron-jobs-ns',owner:'SRE',status:'Open',sla:'8d',kev:false,internet:false,tool:'Aqua Security'},
    {id:'CON-009',score:8.7,title:'Critical OpenSSL in nginx sidecar',cve:'CVE-2024-1234',asset:'ingress-nginx:1.25',owner:'Kubernetes Platform',status:'Open',sla:'18h left',kev:true,internet:true,tool:'Trivy'},
    {id:'CON-010',score:3.9,title:'Non-root user not enforced',cve:null,asset:'legacy-monolith',owner:'Internal Apps',status:'Risk accepted',sla:'30d',kev:false,internet:false,tool:'Sysdig Secure'},
    {id:'CON-011',score:7.5,title:'Capabilities ADD NET_ADMIN',cve:null,asset:'cni-plugin',owner:'Kubernetes Platform',status:'Open',sla:'4d',kev:false,internet:false,tool:'Aqua Security'},
    {id:'CON-012',score:6.1,title:'Image from untrusted registry',cve:null,asset:'ml-training-job',owner:'Data Science',status:'Compensating control',sla:'7d',kev:false,internet:false,tool:'Trivy'},
    {id:'CON-013',score:9.0,title:'RunAsNonRoot=false in prod',cve:null,asset:'admin-console',owner:'Internal Apps',status:'Open',sla:'24h left',kev:false,internet:true,tool:'Sysdig Secure'},
    {id:'CON-014',score:5.7,title:'Secrets mounted as env vars',cve:null,asset:'checkout-api',owner:'E-commerce',status:'In progress',sla:'6d left',kev:false,internet:true,tool:'Aqua Security'},
    {id:'CON-015',score:4.2,title:'Image signature not verified',cve:null,asset:'artifact-cache',owner:'DevEx',status:'Open',sla:'14d',kev:false,internet:false,tool:'Trivy'},
    {id:'CON-016',score:8.3,title:'Shellshock in deprecated base',cve:'CVE-2014-6271',asset:'legacy-etl:v0.9',owner:'Data Platform',status:'Patched',sla:'Closed',kev:false,internet:false,tool:'Trivy'},
    {id:'CON-017',score:6.8,title:'HostPath mount to /var/run/docker.sock',cve:null,asset:'debug-sidecar',owner:'SRE',status:'Open',sla:'3d left',kev:false,internet:false,tool:'Sysdig Secure'},
    {id:'CON-018',score:7.0,title:'Vulnerable Helm chart subchart',cve:'CVE-2023-27163',asset:'service-mesh-chart',owner:'Platform Engineering',status:'Open',sla:'5d',kev:false,internet:true,tool:'Aqua Security'}
  ],
  iac: [
    {id:'IAC-001',score:8.6,title:'Public S3 bucket policy',cve:null,asset:'data-lake.tf',owner:'Data Platform',status:'Open',sla:'24h left',kev:false,internet:true,tool:'Checkov'},
    {id:'IAC-002',score:7.9,title:'0.0.0.0/0 ingress on RDS SG',cve:null,asset:'analytics-stack',owner:'Analytics',status:'In progress',sla:'2d left',kev:false,internet:true,tool:'tfsec'},
    {id:'IAC-003',score:7.2,title:'IAM wildcard *:*',cve:null,asset:'admin-policy.tf',owner:'Cloud Security',status:'Open',sla:'3d left',kev:false,internet:false,tool:'KICS'},
    {id:'IAC-004',score:4.4,title:'Unencrypted RDS instance',cve:null,asset:'staging-db.tf',owner:'Data Platform',status:'Open',sla:'9d',kev:false,internet:false,tool:'Checkov'},
    {id:'IAC-005',score:5.1,title:'CloudTrail logging disabled',cve:null,asset:'audit-baseline.tf',owner:'GRC',status:'Compensating control',sla:'7d',kev:false,internet:false,tool:'tfsec'},
    {id:'IAC-006',score:8.1,title:'EKS public endpoint enabled',cve:null,asset:'eks-cluster.tf',owner:'Kubernetes Platform',status:'Open',sla:'36h left',kev:false,internet:true,tool:'Checkov'},
    {id:'IAC-007',score:6.3,title:'Security group allows all egress',cve:null,asset:'vpc-module',owner:'Network',status:'In progress',sla:'5d left',kev:false,internet:false,tool:'KICS'},
    {id:'IAC-008',score:3.8,title:'S3 versioning not enabled',cve:null,asset:'backup-bucket.tf',owner:'SRE',status:'Risk accepted',sla:'28d',kev:false,internet:false,tool:'tfsec'},
    {id:'IAC-009',score:7.5,title:'Lambda overly permissive role',cve:null,asset:'etl-lambda.tf',owner:'Data Platform',status:'Open',sla:'4d',kev:false,internet:false,tool:'Checkov'},
    {id:'IAC-010',score:5.6,title:'KMS key rotation off',cve:null,asset:'secrets-kms.tf',owner:'Cloud Security',status:'Open',sla:'11d',kev:false,internet:false,tool:'KICS'},
    {id:'IAC-011',score:8.4,title:'Open security group to 0.0.0.0/0:22',cve:null,asset:'bastion.tf',owner:'Network',status:'Open',sla:'12h left',kev:false,internet:true,tool:'tfsec'},
    {id:'IAC-012',score:4.7,title:'Missing S3 public access block',cve:null,asset:'logs-archive.tf',owner:'Observability',status:'Patched',sla:'Closed',kev:false,internet:false,tool:'Checkov'},
    {id:'IAC-013',score:6.9,title:'IAM user long-lived access key',cve:null,asset:'ci-user.tf',owner:'DevEx',status:'Open',sla:'6d',kev:false,internet:false,tool:'KICS'},
    {id:'IAC-014',score:7.7,title:'ALB without WAF association',cve:null,asset:'edge-alb.tf',owner:'Digital Experience',status:'In progress',sla:'3d left',kev:false,internet:true,tool:'Checkov'},
    {id:'IAC-015',score:5.0,title:'EBS volume not encrypted',cve:null,asset:'worker-asg.tf',owner:'Kubernetes Platform',status:'Open',sla:'8d',kev:false,internet:false,tool:'tfsec'},
    {id:'IAC-016',score:3.5,title:'Tag policy noncompliance',cve:null,asset:'org-scp.tf',owner:'Cloud FinOps',status:'Risk accepted',sla:'45d',kev:false,internet:false,tool:'Checkov'},
    {id:'IAC-017',score:8.8,title:'Secrets in Terraform state backend',cve:null,asset:'backend-config.tf',owner:'Platform Engineering',status:'Open',sla:'24h left',kev:false,internet:false,tool:'KICS'},
    {id:'IAC-018',score:6.0,title:'Azure NSG allows RDP from Internet',cve:null,asset:'win-jump.bicep',owner:'Windows Ops',status:'Compensating control',sla:'5d',kev:false,internet:true,tool:'Checkov'}
  ],
  cspm: [
    {id:'CSPM-001',score:9.8,title:'Toxic combo: public S3 + admin IAM + PCI',cve:null,asset:'payments-data-lake',owner:'Payments Platform',status:'Open',sla:'6h left',kev:true,internet:true,tool:'Wiz'},
    {id:'CSPM-002',score:6.5,title:'IAM unused privileges (230)',cve:null,asset:'payments-admin-role',owner:'Cloud Security',status:'In progress',sla:'7d left',kev:false,internet:false,tool:'Prisma Cloud'},
    {id:'CSPM-003',score:8.4,title:'Lateral path: dev EC2 → prod IAM',cve:null,asset:'cloud-graph',owner:'Cloud Security',status:'Open',sla:'24h left',kev:false,internet:false,tool:'Orca Security'},
    {id:'CSPM-004',score:8.9,title:'Public Postgres RDS weak password',cve:null,asset:'analytics-rds-prod',owner:'Analytics',status:'Open',sla:'12h left',kev:true,internet:true,tool:'Microsoft Defender for Cloud'},
    {id:'CSPM-005',score:5.0,title:'Drift: 47 resources outside IaC',cve:null,asset:'prod-account',owner:'Cloud Platform',status:'Open',sla:'10d',kev:false,internet:false,tool:'Wiz'},
    {id:'CSPM-006',score:7.6,title:'S3 bucket MFA delete disabled',cve:null,asset:'audit-logs-bucket',owner:'GRC',status:'Compensating control',sla:'5d',kev:false,internet:false,tool:'Prisma Cloud'},
    {id:'CSPM-007',score:8.2,title:'VM with public IP and local admin',cve:null,asset:'jumpbox-dev-03',owner:'R&D',status:'Open',sla:'2d left',kev:false,internet:true,tool:'Orca Security'},
    {id:'CSPM-008',score:6.8,title:'K8s dashboard exposed',cve:null,asset:'eks-prod-west',owner:'Kubernetes Platform',status:'In progress',sla:'4d left',kev:false,internet:true,tool:'Wiz'},
    {id:'CSPM-009',score:9.2,title:'Internet→S3→Lambda→RDS path',cve:null,asset:'attack-path-014',owner:'Payments Platform',status:'Open',sla:'8h left',kev:true,internet:true,tool:'Wiz'},
    {id:'CSPM-010',score:4.6,title:'Unused security group rules',cve:null,asset:'vpc-prod-01',owner:'Network',status:'Risk accepted',sla:'21d',kev:false,internet:false,tool:'Prisma Cloud'},
    {id:'CSPM-011',score:7.3,title:'Overly broad S3 ACL',cve:null,asset:'marketing-assets',owner:'Marketing Web',status:'Open',sla:'3d left',kev:false,internet:true,tool:'Microsoft Defender for Cloud'},
    {id:'CSPM-012',score:5.9,title:'Azure AD guest invite unrestricted',cve:null,asset:'entra-tenant',owner:'Identity',status:'Open',sla:'8d',kev:false,internet:false,tool:'Prisma Cloud'},
    {id:'CSPM-013',score:8.6,title:'Secrets in Lambda environment',cve:null,asset:'webhook-handler',owner:'Platform Engineering',status:'Open',sla:'18h left',kev:false,internet:true,tool:'Orca Security'},
    {id:'CSPM-014',score:6.2,title:'GCP service account key age >365d',cve:null,asset:'gcp-billing-sa',owner:'Cloud FinOps',status:'In progress',sla:'6d left',kev:false,internet:false,tool:'Wiz'},
    {id:'CSPM-015',score:7.8,title:'CNAPP: malware in running workload',cve:null,asset:'payments-pod-7f2a',owner:'Payments Platform',status:'Open',sla:'24h left',kev:false,internet:true,tool:'Orca Security'},
    {id:'CSPM-016',score:3.9,title:'Non-prod account missing guardrail',cve:null,asset:'sandbox-12',owner:'Cloud Platform',status:'Patched',sla:'Closed',kev:false,internet:false,tool:'Prisma Cloud'},
    {id:'CSPM-017',score:8.7,title:'IAM passRole to admin role',cve:null,asset:'cicd-deployer',owner:'DevEx',status:'Open',sla:'36h left',kev:false,internet:false,tool:'Wiz'},
    {id:'CSPM-018',score:5.4,title:'Logging bucket not immutable',cve:null,asset:'siem-archive',owner:'SecOps',status:'Compensating control',sla:'9d',kev:false,internet:false,tool:'Microsoft Defender for Cloud'}
  ],
  easm: [
    {id:'EASM-001',score:9.1,title:'Exposed Jenkins instance',cve:null,asset:'ci-old.example.com',owner:'DevEx',status:'Open',sla:'12h left',kev:true,internet:true,tool:'Censys'},
    {id:'EASM-002',score:7.6,title:'Subdomain takeover (dangling CNAME)',cve:null,asset:'coupons.example.com',owner:'Marketing Web',status:'In progress',sla:'3d left',kev:false,internet:true,tool:'Randori'},
    {id:'EASM-003',score:9.3,title:'Public Elasticsearch no auth',cve:null,asset:'acme-acquired.example.net',owner:'M&A Integration',status:'Open',sla:'8h left',kev:false,internet:true,tool:'Palo Alto Xpanse'},
    {id:'EASM-004',score:5.5,title:'Expired wildcard certificate',cve:null,asset:'*.partners.example.com',owner:'Partner Integrations',status:'Open',sla:'7d',kev:false,internet:true,tool:'Censys'},
    {id:'EASM-005',score:6.8,title:'Shadow IT: hosts not in CMDB',cve:null,asset:'23 internet hosts',owner:'SecOps',status:'Open',sla:'5d',kev:false,internet:true,tool:'Randori'},
    {id:'EASM-006',score:8.4,title:'Exposed Kubernetes API',cve:null,asset:'k8s-lab.example.com',owner:'R&D',status:'Open',sla:'24h left',kev:true,internet:true,tool:'Palo Alto Xpanse'},
    {id:'EASM-007',score:4.1,title:'Typosquat domain registered',cve:null,asset:'examp1e.com',owner:'Brand Protection',status:'In progress',sla:'14d left',kev:false,internet:true,tool:'Censys'},
    {id:'EASM-008',score:7.2,title:'Git repository exposed via .git',cve:null,asset:'dev.example.com',owner:'DevEx',status:'Open',sla:'2d left',kev:false,internet:true,tool:'Randori'},
    {id:'EASM-009',score:8.8,title:'Citrix ADC login panel internet',cve:null,asset:'remote.example.com',owner:'Network',status:'Compensating control',sla:'1d',kev:true,internet:true,tool:'Palo Alto Xpanse'},
    {id:'EASM-010',score:5.9,title:'Open MongoDB on non-standard port',cve:null,asset:'db-leak-44.example.net',owner:'Data Platform',status:'Open',sla:'48h left',kev:false,internet:true,tool:'Censys'},
    {id:'EASM-011',score:3.7,title:'SPF record missing',cve:null,asset:'mail.example.com',owner:'Messaging',status:'Risk accepted',sla:'30d',kev:false,internet:true,tool:'Censys'},
    {id:'EASM-012',score:9.0,title:'RDP on residential ISP IP',cve:null,asset:'185.12.x.x',owner:'Unknown',status:'Open',sla:'6h left',kev:true,internet:true,tool:'Randori'},
    {id:'EASM-013',score:6.4,title:'WordPress admin reachable',cve:null,asset:'blog.example.com',owner:'Marketing Web',status:'In progress',sla:'4d left',kev:false,internet:true,tool:'Palo Alto Xpanse'},
    {id:'EASM-014',score:7.9,title:'Exposed .env backup file',cve:null,asset:'cdn-static.example.com',owner:'Digital Experience',status:'Open',sla:'36h left',kev:false,internet:true,tool:'Censys'},
    {id:'EASM-015',score:4.8,title:'Certificate transparency new subdomain',cve:null,asset:'pay-staging.example.com',owner:'Payments Platform',status:'Open',sla:'10d',kev:false,internet:true,tool:'Randori'},
    {id:'EASM-016',score:8.1,title:'VPN portal pre-auth RCE',cve:'CVE-2024-21762',asset:'vpn.example.com',owner:'Network',status:'Open',sla:'18h left',kev:true,internet:true,tool:'Palo Alto Xpanse'},
    {id:'EASM-017',score:5.2,title:'SMB signing not required',cve:null,asset:'fileshare.example.com',owner:'Windows Ops',status:'Patched',sla:'Closed',kev:false,internet:true,tool:'Censys'},
    {id:'EASM-018',score:6.6,title:'M&A asset: exposed SonarQube',cve:null,asset:'sonar.acme-acquired.net',owner:'M&A Integration',status:'Open',sla:'5d',kev:false,internet:true,tool:'Randori'}
  ],
  secrets: [
    {id:'SEC-001',score:10.0,title:'AWS access key in public gist',cve:null,asset:'github-gist AKIA...',owner:'Payments Platform',status:'Open',sla:'1h left',kev:false,internet:true,tool:'GitGuardian'},
    {id:'SEC-002',score:7.4,title:'OAuth token in commit history',cve:null,asset:'backend-svc repo',owner:'Platform Engineering',status:'In progress',sla:'2d left',kev:false,internet:false,tool:'TruffleHog'},
    {id:'SEC-003',score:8.0,title:'DB connection string with password',cve:null,asset:'config-old.json',owner:'Data Platform',status:'Open',sla:'24h left',kev:false,internet:false,tool:'GitHub Advanced Security'},
    {id:'SEC-004',score:8.7,title:'Private SSH key in repo',cve:null,asset:'deployment-scripts',owner:'DevEx',status:'Open',sla:'12h left',kev:false,internet:false,tool:'GitGuardian'},
    {id:'SEC-005',score:6.9,title:'Hard-coded password campaign (12 repos)',cve:null,asset:'12 repositories',owner:'Security Engineering',status:'In progress',sla:'4d left',kev:false,internet:false,tool:'TruffleHog'},
    {id:'SEC-006',score:8.6,title:'Stripe API key in container image',cve:null,asset:'payments-svc:v2.1',owner:'Payments Platform',status:'Open',sla:'18h left',kev:false,internet:true,tool:'GitGuardian'},
    {id:'SEC-007',score:9.2,title:'Azure service principal secret live',cve:null,asset:'infra-terraform PR #882',owner:'Cloud Platform',status:'Open',sla:'6h left',kev:false,internet:false,tool:'GitHub Advanced Security'},
    {id:'SEC-008',score:5.8,title:'Slack webhook URL in README',cve:null,asset:'oncall-bot',owner:'SRE',status:'Patched',sla:'Closed',kev:false,internet:true,tool:'TruffleHog'},
    {id:'SEC-009',score:7.9,title:'GCP JSON key in artifact bucket',cve:null,asset:'gs://build-artifacts',owner:'DevEx',status:'Open',sla:'36h left',kev:false,internet:true,tool:'GitGuardian'},
    {id:'SEC-010',score:4.5,title:'Test API key (revoked)',cve:null,asset:'integration-tests',owner:'QA',status:'Risk accepted',sla:'30d',kev:false,internet:false,tool:'TruffleHog'},
    {id:'SEC-011',score:8.3,title:'Datadog API key in Helm values',cve:null,asset:'observability-chart',owner:'Observability',status:'In progress',sla:'2d left',kev:false,internet:false,tool:'GitHub Advanced Security'},
    {id:'SEC-012',score:7.1,title:'PagerDuty token in CI env',cve:null,asset:'.github/workflows',owner:'SRE',status:'Open',sla:'3d left',kev:false,internet:false,tool:'GitGuardian'},
    {id:'SEC-013',score:9.5,title:'Production DB password in ticket paste',cve:null,asset:'Jira export attachment',owner:'Finance Systems',status:'Open',sla:'4h left',kev:false,internet:false,tool:'GitGuardian'},
    {id:'SEC-014',score:6.3,title:'JWT signing key in mobile repo',cve:null,asset:'ios-app-config',owner:'Mobile',status:'Compensating control',sla:'6d',kev:false,internet:false,tool:'TruffleHog'},
    {id:'SEC-015',score:8.8,title:'Twilio auth token validated live',cve:null,asset:'notify-svc commit abc12',owner:'Messaging',status:'Open',sla:'24h left',kev:false,internet:true,tool:'GitGuardian'},
    {id:'SEC-016',score:5.4,title:'Base64-encoded secret in config map',cve:null,asset:'k8s-manifests',owner:'Kubernetes Platform',status:'Open',sla:'8d',kev:false,internet:false,tool:'GitHub Advanced Security'},
    {id:'SEC-017',score:7.6,title:'Salesforce connected app secret',cve:null,asset:'crm-sync',owner:'Sales Ops',status:'In progress',sla:'5d left',kev:false,internet:false,tool:'TruffleHog'},
    {id:'SEC-018',score:9.8,title:'Root AWS key in public S3 object',cve:null,asset:'s3://leaked-backup-2023',owner:'Incident Response',status:'Open',sla:'Overdue 1h',kev:false,internet:true,tool:'GitGuardian'}
  ]
};
